### ISSUE TITLE
Feed Filter From Whom - Clear Filter

### ISSUE THREAD

**Issue by Mohammedks713** [FightPandemics/FightPandemics-iOS#144] opened 2020-05-21 22:26 UTC
NOTE: This is ONLY for the Clear Filters portion of the UI - NOT the From whom title, the - button, the Tags, or the Apply filters button

- Pill button with light theme
- Upon tapping - closes From Whom (if open); clears Tag selection (if made)
- Localized

**Comment by devarshjoshi** [comment] 2020-05-23 03:54
Closing this as it is duplicate of #127

**Closed as completed by devarshjoshi** 2020-05-23 03:54 UTC
